### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by stefanjarina** [stefanjarina/FCC-Go-wiki#1]
This repo is purely to track my work on Go wiki for FCC

- [ ] [Introduction](Go-Introduction)
  - [ ] [Installation](Go-Introduction#Installation)
    - [ ] [System Packages](Go-Introduction#System Packages)
    - [ ] [GVM](Go-Introduction#GVM)
  - [ ] [Editors](Go-Introduction#Editors)
    - [ ] [VIM](Go-Introduction#VIM)
    - [ ] [Emacs](Go-Introduction#Emacs)  (No idea about this one, someone else might write it)
    - [ ] [Atom](Go-Introduction#Atom)
    - [ ] [VSCode](Go-Introduction#VSCode)
    - [ ] [LiteIDE](Go-Introduction#LiteIDE)
- [ ] [Language Fundamentals](Go-Language-Fundamentals)
  - [ ] [Spec](Go-Language-Fundamentals#Spec) (Formatting, Commentary, Names)
  - [ ] [Packages](Go-Language-Fundamentals#Packages)
  - [ ] [Go Commands](Go-Language-Fundamentals#Go Commands)
  - [ ] [Variables](Go-Language-Fundamentals#Variables)
  - [ ] [Scope](Go-Language-Fundamentals#Scope)
  - [ ] [Pointers](Go-Language-Fundamentals#Pointers)
- [ ] [Control Flow](Go-Control-Flow)
  - [ ] [For Loop](Go-Control-Flow#For Loop)
  - [ ] [Conditions, Break & Continue](Go-Control-Flow#Conditions, Break & Continue)
  - [ ] [Switch Statement](Go-Control-Flow#Switch Statement)
  - [ ] [If Statement](Go-Control-Flow#If Statement)
- [ ] [Functions](Go-Functions)
- [ ] [Data Structures](Go-Data-Structures)
  - [ ] [Array](Go-Data-Structures#Array)
  - [ ] [Slice](Go-Data-Structures#Slice)
  - [ ] [Map](Go-Data-Structures#Map)
  - [ ] [Struct](Go-Data-Structures#Struct)
- [ ] [Interfaces](Go-Interfaces)
- [ ] [Concurrency](Go-Concurrency)
- [ ] [Channels](Go-Channels)
- [ ] [Web-development in Go](Go-Web-Development) (Probably Beego web Framework)
- [ ] [Write simple API in Gin-Gonic](Go-Gin-Gonic)
- [ ] [Other Resources](Go-Other-Resources) (Links to other resources)
